language: ruby
dist: xenial
rvm:
  - 2.4.5

before_install:
  - gem update --system
  - gem install bundler

gemfile: .gemfile

script:
  - "puppet-lint \
     --fail-on-warnings \
     `find modules -name '*.pp'`"
