language: ruby
dist: xenial
rvm:
  - 2.4.5

before_install:
  - gem update --system
  - gem install bundler

gemfile: ".gemfile"

script:
  - "puppet-lint --fail-on-warnings `find modules -name '*.pp'`"

notifications:
  irc:
    channels:
    - secure: "EgaXYzcv5K4Hy2vRc9lVMGJ6INK4WiWRLU2X3l0bAky1a234EjI+7w+98FYZfZNFrKSA1xK8jtBnqqwSTmqAXmbL7G6VP8+5PX1wQH5mBO+i9z5MGavUwJ4TfnL6KvxAapS0goPbmJWgAlKxS/dXWDpe5RVx/UwvYp5mjQKqbYuiDG01LqjJdSQGQV+CgVQc4yjq0a4Q/ulJutkQTlm9xyQ7YxPijHhdClSS/kUgNdq9OAiovK8H3RVcVtmdOZkorcWCdU2lOWBwLM+XILNB2iU/rfur2ivjXXWRVvVanAKYXDrjprGo8mscJ20bMR4pxaxr0SN7P36UxD4G6llpRecYwgrlzJKvfABFWWTnWE6qHp5UkmkAjVHwDsnvlrUDCTM4RSs3EnwHQXqPUQJXnYa5WWjzcf0ez+dy4DbiE92NBCGZoAVPLyVdCFn47/ErFz8tJkb8vWIxGa4kJqMzo5NquVYJfWMqVts3AKwP2/n93jRyOk8rDIOpeOdtXmDWZyOPNF38CtO2SXjegZDbtrSq7uwpbqf6QRdvxX/VPWc5os6XYRc5lzlUgP6jeRLSIjtlVN1/oN5FVuTi4kIm2mnaKcWCrjjraVlT9N0QaTX50ADkWnd+zjjzuuO4pLU8+K0x8HWsBMSCpj7GXGao0DBSGwBDKTqG9ZWUCthXEi4="
    skip_join: true
    use_notice: true
    on_success: always
    on_failure: always
    template:
    - "\x02%{repository_name}\x0314#%{build_number}\x03\x02 (%{branch} - %{commit}: %{author}): \x02\x0312%{message}\x02\x03 (\x0314%{build_url}\x03)"
