version: 2.1

jobs:
  pre_commit:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip3 install pre-commit
      - run: pre-commit run --all-files
  r10k_install:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - run: bundle exec r10k puppetfile install --moduledir=/tmp/r10k_module_test -v --force
  # matrix_test:
  #   docker:
  #     - image: circleci/python:3.9.1
  #   parameters:
  #     a:
  #       type: string
  #   steps:
  #     - run: echo "123 << parameters.a >>"
  kitchen_converge_and_verify:
    docker:
      - image: circleci/ruby:2.7.2
    parameters:
      a:
        type: string
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - run: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen converge << parameters.a >>
      - run: KITCHEN_YAML=.kitchen.docker.yml bundle exec kitchen verify << parameters.a >>

workflows:
  ci_test:
    jobs:
      # - pre_commit
      # - r10k_install
      # - matrix_test:
      #     matrix:
      #       parameters:
      #         a: ['a']
      - kitchen_converge_and_verify:
          # pre-steps:
          #   - run:
          #       command: echo "test 456"
          #   - setup_remote_docker:
          #     version: 19.03.13
          matrix:
            parameters:
              a: ["bitbar", "linux", "maas-region", "maas-rack"]
